/*
 * ============================================================================
 *  SMART CANE CLIP-ON  |  YOLOv8 TFLite Object Detector
 * ============================================================================
 *  Loads yolov8n_320_float16.tflite from app assets and runs inference on
 *  a Bitmap.  Handles:
 *    • Pre-processing  : resize → 320×320, normalize to [0, 1]
 *    • Post-processing : parse [1, 84, 2100] output, confidence filter, NMS
 *    • Label filtering : only returns classes relevant to pedestrian safety
 *
 *  ASSET REQUIRED
 *  --------------
 *  Place  yolov8n_320_float16.tflite  in  app/src/main/assets/
 *  (generated by export_yolo_tflite.py)
 *
 *  DEPENDENCIES (app/build.gradle.kts)
 *  ------------------------------------
 *  implementation("org.tensorflow:tensorflow-lite:2.14.0")
 *  implementation("org.tensorflow:tensorflow-lite-support:0.4.4")
 *  implementation("org.tensorflow:tensorflow-lite-gpu:2.14.0")
 * ============================================================================
 */

package com.smartcane.gateway

import android.content.Context
import android.graphics.Bitmap
import android.graphics.RectF
import org.tensorflow.lite.Interpreter
import org.tensorflow.lite.gpu.GpuDelegate
import org.tensorflow.lite.support.common.FileUtil
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.max
import kotlin.math.min

data class DetectionResult(
    val label: String,
    val confidence: Float,
    val boundingBox: RectF          // normalized [0,1] coordinates
)

class TfliteObjectDetector(context: Context) : AutoCloseable {

    companion object {
        private const val MODEL_FILE     = "yolov8n_320_float16.tflite"
        private const val INPUT_SIZE     = 320
        private const val CONF_THRESHOLD = 0.35f
        private const val IOU_THRESHOLD  = 0.45f
        private const val NUM_ANCHORS    = 2100   // for 320×320 input
        private const val NUM_COORDS     = 4
        private const val NUM_CLASSES    = 80

        // COCO class indices relevant to pedestrian / outdoor navigation
        private val RELEVANT_CLASSES = setOf(
            0,  // person
            1,  // bicycle
            2,  // car
            3,  // motorcycle
            5,  // bus
            7,  // truck
            9,  // traffic light
            11, // stop sign
            13, // bench
            15, // cat
            16, // dog
            56, // chair
            57, // couch
            58, // potted plant
            60, // dining table (edge cases indoors)
            63, // laptop (indoors)
        )

        // Subset of COCO 80-class labels
        private val COCO_LABELS = arrayOf(
            "person","bicycle","car","motorcycle","airplane","bus","train","truck","boat",
            "traffic light","fire hydrant","stop sign","parking meter","bench","bird","cat",
            "dog","horse","sheep","cow","elephant","bear","zebra","giraffe","backpack",
            "umbrella","handbag","tie","suitcase","frisbee","skis","snowboard","sports ball",
            "kite","baseball bat","baseball glove","skateboard","surfboard","tennis racket",
            "bottle","wine glass","cup","fork","knife","spoon","bowl","banana","apple",
            "sandwich","orange","broccoli","carrot","hot dog","pizza","donut","cake","chair",
            "couch","potted plant","bed","dining table","toilet","tv","laptop","mouse",
            "remote","keyboard","cell phone","microwave","oven","toaster","sink","refrigerator",
            "book","clock","vase","scissors","teddy bear","hair drier","toothbrush"
        )
    }

    private val gpuDelegate = runCatching { GpuDelegate() }.getOrNull()
    private val interpreter: Interpreter

    init {
        val model = FileUtil.loadMappedFile(context, MODEL_FILE)
        val opts  = Interpreter.Options().apply {
            if (gpuDelegate != null) addDelegate(gpuDelegate)
            else numThreads = 4
        }
        interpreter = Interpreter(model, opts)
    }

    /**
     * Run inference on [bitmap].  Returns detections sorted by confidence (highest first).
     * Safe to call from any thread — does NOT touch the UI.
     */
    fun detect(bitmap: Bitmap): List<DetectionResult> {
        val resized    = Bitmap.createScaledBitmap(bitmap, INPUT_SIZE, INPUT_SIZE, true)
        val inputBuf   = bitmapToByteBuffer(resized)
        // output shape: [1, 84, 2100]  →  [1][84][2100]
        val outputBuf  = Array(1) { Array(NUM_COORDS + NUM_CLASSES) { FloatArray(NUM_ANCHORS) } }

        interpreter.run(inputBuf, outputBuf)

        val raw = outputBuf[0]   // [84][2100]
        val candidates = mutableListOf<DetectionResult>()

        for (a in 0 until NUM_ANCHORS) {
            val cx = raw[0][a]
            val cy = raw[1][a]
            val w  = raw[2][a]
            val h  = raw[3][a]

            var bestScore = CONF_THRESHOLD
            var bestClass = -1
            for (c in 0 until NUM_CLASSES) {
                val score = raw[NUM_COORDS + c][a]
                if (score > bestScore && c in RELEVANT_CLASSES) {
                    bestScore = score
                    bestClass = c
                }
            }
            if (bestClass == -1) continue

            // cx, cy, w, h are in pixels relative to INPUT_SIZE — normalize to [0,1]
            val x1 = ((cx - w / 2f) / INPUT_SIZE).coerceIn(0f, 1f)
            val y1 = ((cy - h / 2f) / INPUT_SIZE).coerceIn(0f, 1f)
            val x2 = ((cx + w / 2f) / INPUT_SIZE).coerceIn(0f, 1f)
            val y2 = ((cy + h / 2f) / INPUT_SIZE).coerceIn(0f, 1f)

            candidates.add(DetectionResult(
                label       = COCO_LABELS.getOrElse(bestClass) { "object" },
                confidence  = bestScore,
                boundingBox = RectF(x1, y1, x2, y2)
            ))
        }

        return nonMaxSuppression(candidates).sortedByDescending { it.confidence }
    }

    // ------------------------------------------------------------------
    //  Pre-processing
    // ------------------------------------------------------------------
    private fun bitmapToByteBuffer(bitmap: Bitmap): ByteBuffer {
        val buf = ByteBuffer.allocateDirect(1 * INPUT_SIZE * INPUT_SIZE * 3 * 4)
            .order(ByteOrder.nativeOrder())
        val pixels = IntArray(INPUT_SIZE * INPUT_SIZE)
        bitmap.getPixels(pixels, 0, INPUT_SIZE, 0, 0, INPUT_SIZE, INPUT_SIZE)
        for (px in pixels) {
            buf.putFloat(((px shr 16) and 0xFF) / 255f)  // R
            buf.putFloat(((px shr 8)  and 0xFF) / 255f)  // G
            buf.putFloat(( px         and 0xFF) / 255f)  // B
        }
        buf.rewind()
        return buf
    }

    // ------------------------------------------------------------------
    //  Greedy NMS
    // ------------------------------------------------------------------
    private fun nonMaxSuppression(dets: List<DetectionResult>): List<DetectionResult> {
        val sorted  = dets.sortedByDescending { it.confidence }.toMutableList()
        val kept    = mutableListOf<DetectionResult>()
        val removed = BooleanArray(sorted.size)

        for (i in sorted.indices) {
            if (removed[i]) continue
            kept.add(sorted[i])
            for (j in i + 1 until sorted.size) {
                if (!removed[j] && iou(sorted[i].boundingBox, sorted[j].boundingBox) > IOU_THRESHOLD) {
                    removed[j] = true
                }
            }
        }
        return kept
    }

    private fun iou(a: RectF, b: RectF): Float {
        val interX1 = max(a.left,   b.left)
        val interY1 = max(a.top,    b.top)
        val interX2 = min(a.right,  b.right)
        val interY2 = min(a.bottom, b.bottom)
        val interW  = max(0f, interX2 - interX1)
        val interH  = max(0f, interY2 - interY1)
        val interArea = interW * interH
        val unionArea = (a.right - a.left) * (a.bottom - a.top) +
                        (b.right - b.left) * (b.bottom - b.top) - interArea
        return if (unionArea <= 0f) 0f else interArea / unionArea
    }

    override fun close() {
        interpreter.close()
        gpuDelegate?.close()
    }
}
